
### Recuperar todas las películas
GET http://localhost:3000/players

### Recuperar una película por id
GET http://localhost:3000/players/5c5f5979-755d-4dd9-956b-23f10d118a82

### Recuperar todas las películas por un género
GET http://localhost:3000/players?position=gk

### Crear una película con POST
POST http://localhost:3000/players
Content-Type: application/json

{
    "name": "Neil Turner",
    "nickname": "",
    "element": "Fire",
    "gender": "Male",
    "position": "DEL",
    "year": "2º",
    "sprite": "https://static.wikia.nocookie.net/inazuma/images/9/91/%28B%29_Turner.png"
}

### Actualizar una película
PATCH http://localhost:3000/players/0a947a75-024b-419b-b4ef-e3106b0e38e3
Content-Type: application/json

{
  "name": "El nelas"
}
###
DELETE http://localhost:3000/players/0a947a75-024b-419b-b4ef-e3106b0e38e3