
### Recuperar todas las películas
GET http://localhost:3000/players

### Recuperar una película por id
GET http://localhost:3000/players/e962498e-cd60-47a3-8e02-5916a4a8fc1d

### Recuperar todas las películas por un género
GET http://localhost:3000/players?position=FW

### Crear una película con POST
POST http://localhost:3000/players
Content-Type: application/json

{
  "name": "Mark Evans",
  "nickname": null,
  "element": "Earth",
  "gender": "Male",
  "position": "GK",
  "year": "2º",
  "sprite": "https://static.wikia.nocookie.net/inazuma-eleven/images/d/dd/%28R%29_Endou_Mamoru_sprite_%28VR%29.png"
}

### Actualizar una película
PATCH http://localhost:3000/players/e962498e-cd60-47a3-8e02-5916a4a8fc1d
Content-Type: application/json

{
  "position": "FW"
}
###
DELETE http://localhost:3000/players/e962498e-cd60-47a3-8e02-5916a4a8fc1d